import pathlib,json,hashlib,re,subprocess,datetime,collections
r=pathlib.Path(__file__).resolve().parent;cloud=pathlib.Path('/srv/cloud/technical-documentation/lenovo');manifest=json.loads((r/'audit/manifest.json').read_text());baseline=json.loads((r/'baseline.json').read_text());batch=[json.loads(p.read_text()) for p in sorted((r/'out/batch-records').glob('*.json'))];reviews=[json.loads(p.read_text()) for p in sorted((r/'out/reviews').glob('*.json'))]
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();expected={x['path']:x for x in manifest['documents']};actual={str(p.relative_to(cloud/'cleaned')):sha(p) for p in (cloud/'cleaned').rglob('*') if p.is_file()};originals=[dict(x,sha256_after=sha(cloud/'originals'/x['path'])) for x in manifest['documents']];index=json.loads(re.search(r'<script id="catalog-data" type="application/json">(.*?)</script>',(cloud/'originals/INDEX.html').read_text(),re.S)[1]);index_by_path={x['path']:x for x in index['documents']};runtime=json.loads(pathlib.Path('/opt/pdf-cleanup/deployment.json').read_text());source_commit=subprocess.check_output(['git','-C','/opt/pdf-cleanup/source','rev-parse','HEAD'],text=True).strip();job_shas={str(p):sha(p) for p in map(pathlib.Path,('/opt/pdf-cleanup/run','/opt/pdf-cleanup/job-command.py'))};old=json.loads((r/'old-deployment.json').read_text())
checks={'95_original_hashes_unchanged':all(x['sha256_after']==x['sha256'] for x in originals),'original_path_set_unchanged':{str(p.relative_to(cloud/'originals')) for p in (cloud/'originals').rglob('*.pdf')}==set(expected),'95_batch_successes':len(batch)==len(expected) and all(x['status']=='passed' and x['job_removed'] for x in batch),'95_independent_successes':len(reviews)==len(expected) and all(x['status']=='passed' for x in reviews),'cleaned_path_set_matches_originals':set(actual)==set(expected),'cleaned_bytes_match_verified_outputs':all(actual.get(x['path'])==x['output_sha256'] for x in reviews),'index_95_cleaned_markers':set(index_by_path)==set(expected) and all(x.get('cleanup_status')=='cleaned' and x.get('cleaned_path')==x['path'] and x.get('cleaned_at') for x in index['documents']),'INDEX_md_unchanged':next(x['sha256'] for x in baseline if x['path']==str(cloud/'originals/INDEX.md'))==sha(cloud/'originals/INDEX.md'),'launcher_unchanged':job_shas['/opt/pdf-cleanup/run']=='40d440ae6e30e475bee0e49de8df085d75bac1643679dec879d4c8e449265092','adapter_unchanged':job_shas['/opt/pdf-cleanup/job-command.py']==old['job_adapter_sha256'],'source_commit_matches_manifest':source_commit==runtime['source_commit'],'image_identity_matches_manifest':subprocess.check_output(['docker','image','inspect',runtime['image_tag'],'--format','{{.Id}}'],text=True).strip()==runtime['image_id'],'source_git_clean':subprocess.check_output(['git','-C','/opt/pdf-cleanup/source','status','--porcelain'],text=True)==''}
pattern=re.compile(r'(<script id="catalog-data" type="application/json">)([\s\S]*?)(</script>)')
initial_html=(r/'index-initial.html').read_text();final_html=(cloud/'originals/INDEX.html').read_text();initial=json.loads(pattern.search(initial_html)[2]);strip=lambda d:{k:v for k,v in d.items() if k not in ('cleanup_status','cleaned_at','cleaned_path')}
checks['catalogue_source_dates_titles_records_preserved']={d['path']:strip(d) for d in initial['documents']}=={d['path']:strip(d) for d in index['documents']}
checks['index_interface_unchanged']=pattern.sub(lambda m:m[1]+m[3],initial_html)==pattern.sub(lambda m:m[1]+m[3],final_html)
checks['cli_stderr_empty']=all(not x.get('adapter_result',{}).get('stderr') for x in batch)
checks['repeat_targets_zero']=all(not x.get('repeat_analysis',{}).get('targets') for x in reviews)
others=[x for x in baseline if '/translated/' in x['path']];checks['translations_unchanged']=all(sha(pathlib.Path(x['path']))==x['sha256'] for x in others)
result={'checked_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'checks':checks,'status':'passed' if all(checks.values()) else 'failed','originals':originals,'cleaned_sha256':actual,'models':len({x['path'].split('/')[0] for x in manifest['documents']}),'unique_original_contents':len(manifest['unique_documents']),'all_path_pages':sum(x.get('independent',{}).get('pages',0) for x in reviews),'body_glyphs':sum(x.get('independent',{}).get('body_glyphs',0) for x in reviews),'pixels_outside_masks':sum(x.get('independent',{}).get('pixels_outside_masks',0) for x in reviews),'runtime':runtime}
(r/'final-audit.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:v for k,v in result.items() if k not in ('originals','cleaned_sha256','runtime')},ensure_ascii=False));assert all(checks.values())
