[Definition]
datepattern = %%Y-%%m-%%dT%%H:%%M:%%SZ
failregex = ^.*Relay not allowed \(smtp\.relay-not-allowed\).*remoteIp = <HOST>,.*$
            ^.*Authentication not allowed \(smtp\.auth-not-allowed\).*remoteIp = <HOST>.*$
ignoreregex =
