const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const directory = process.argv[2];
const fixture = JSON.parse(fs.readFileSync(__dirname+'/test-fixtures.json','utf8'));
const nodes = JSON.parse(fs.readFileSync(directory+'/nodes.json'));
const html = '<!doctype html><script id="catalog-data" type="application/json">'+JSON.stringify(fixture.catalog)+'</script><div class="noscript"></div>';
const catalog = JSON.parse(html.match(/<script id="catalog-data" type="application\/json">([\s\S]*?)<\/script>/)[1]);
const asp = fixture.asp;
async function run(name,input,previous={}) {
  const source = nodes.find(n=>n.name===name).parameters.jsCode;
  const context = vm.createContext({$input:{all:()=>input,first:()=>input[0]},
    $:name=>({all:()=>previous[name],first:()=>previous[name][0]}),
    $now:{toISO:()=> '2026-10-05T14:00:00+03:00'}});
  return JSON.parse(JSON.stringify(await vm.runInContext('(async function(){'+source+'})()',context)));
}
(async()=>{
  const allModels = await run('Models and Index',[]);
  const models = allModels.filter(item=>item.json.model.folder==='WR5220 G3');
  assert.equal(allModels.length,14);
  const families = await run('Latest Document Families',[{json:{body:asp}}],{'Models and Index':models});
  assert.equal(families.length,15);
  assert.equal(families.find(d=>d.json.key.endsWith('/bmc-event-reference')).json.path,'WR5220 G3/lenovo_bmc_event_reference_guide_g5_v4.pdf');
  assert.equal(families.filter(d=>d.json.key.endsWith('/lxpm-user-guide')).length,1);
  const headers = families.map(({json:d})=>{
    const v=catalog.documents.find(old=>old.key===d.key)?.remote_validator;
    return {json:{headers:{etag:v?.etag??'"new"','last-modified':v?.last_modified??'Tue, 21 Apr 2026 10:00:00 GMT','content-length':String(v?.content_length??12345)}}};
  });
  const previous={'Read INDEX':[{json:{data:html}}],'Latest Document Families':families};
  let changed = await run('Changed Documents',headers,previous);
  assert.deepEqual(changed.map(x=>x.json.key.split('/')[1]).sort(),['bios-setup-specification','psu-label-matrix','vmware-code-recipe']);
  const manual = families.findIndex(d=>d.json.key.endsWith('/user-manual'));
  const revised = structuredClone(headers); revised[manual].json.headers.etag='"replacement"';
  changed = await run('Changed Documents',revised,previous);
  assert(changed.some(d=>d.json.key.endsWith('/user-manual')));
  const renamed=structuredClone(families); renamed[manual].json.source_url=renamed[manual].json.source_url.replace('v18','v19');renamed[manual].json.path=renamed[manual].json.path.replace('v18','v19');
  changed=await run('Changed Documents',revised,{...previous,'Latest Document Families':renamed});
  const doc=changed.find(d=>d.json.key.endsWith('/user-manual')).json;
  assert(doc.old_path.endsWith('v18.pdf')); assert(doc.path.endsWith('v19.pdf'));
  assert.equal(doc.title,'User Manual Lenovo Wentian WR5220 G3');
  assert.equal(doc.previous_source_updated,catalog.documents.find(d=>d.key===doc.key).source_updated);
  assert(changed.filter(d=>!catalog.documents.some(old=>old.key===d.json.key)).every(d=>d.json.previous_source_updated===null));
  const nextCatalog=structuredClone(catalog);
  const priorRecord=nextCatalog.documents.find(d=>d.key===doc.key);
  priorRecord.previous_source_updated='2026-01-01';
  priorRecord.source_updated='2026-10-05';
  const nextHtml='<script id="catalog-data" type="application/json">'+JSON.stringify(nextCatalog)+'</script>';
  const nextChanges=await run('Changed Documents',revised,{...previous,'Read INDEX':[{json:{data:nextHtml}}]});
  assert.equal(nextChanges.find(d=>d.json.key===doc.key).json.previous_source_updated,'2026-10-05');
  const other=structuredClone(models);other[0].json.model.folder='Second Model';
  const additional=await run('Latest Document Families',[{json:{body:asp}}],{'Models and Index':other});
  assert(additional.every(d=>d.json.key.startsWith('Second Model/')&&d.json.path.startsWith('Second Model/')));
  const rendered=await run('Update INDEX',[{json:{...doc,title:'<script>PDF</script>',size:12345,remote_validator:{etag:'"replacement"'},edition:null,pages:null,previous_path:doc.old_path}}],{'Read INDEX':[{json:{data:html}}]});
  assert(rendered[0].json.html.includes('&lt;script&gt;PDF&lt;/script&gt;'));
  const updated=JSON.parse(rendered[0].json.html.match(/<script id="catalog-data" type="application\/json">([\s\S]*?)<\/script>/)[1]);
  assert.equal(updated.documents.length,12);
  assert(updated.documents.find(d=>d.key===doc.key).path.endsWith('v19.pdf'));
  assert.equal(rendered[0].json.files[0].path,doc.path);
  assert.equal(rendered[0].json.files[0].previous_path,doc.old_path);
  assert.equal(updated.documents.find(d=>d.key===doc.key).previous_path,undefined);
  assert.equal(updated.documents.find(d=>d.key===doc.key).previous_source_updated,doc.previous_source_updated);
  const cleanupNode=nodes.find(n=>n.name==='Clean Saved PDFs');
  assert.equal(cleanupNode.parameters.mode,'once');
  assert.equal(cleanupNode.parameters.options.waitForSubWorkflow,true);
  await assert.rejects(()=>run('Latest Document Families',[{json:{body:{status:500}}}],{'Models and Index':models}));
  const audit=JSON.parse(fs.readFileSync(__dirname+'/source-audit-2026-10-05.json','utf8'));
  const fresh=JSON.parse(fs.readFileSync(__dirname+'/test-fixtures-models.json','utf8'));
  const inputs=allModels.map(({json:{model}})=>({json:{body:fresh.find(row=>row.folder===model.folder).body}}));
  const combined=await run('Latest Document Families',inputs,{'Models and Index':allModels});
  assert.equal(combined.length,95);
  assert.equal(new Set(combined.map(item=>item.json.key)).size,95);
  const g3Audit=JSON.parse(fs.readFileSync(__dirname+'/source-audit-g3-2026-10-05.json','utf8'));
  assert.equal(combined.filter(item=>g3Audit.models.some(group=>group.folder===item.json.folder)).length,17);
  for (const group of [...audit.models,...g3Audit.models]) {
    const actual=combined.filter(item=>item.json.folder===group.folder);
    assert.deepEqual(actual.map(item=>item.json.path.split('/').pop()).sort(),group.documents.map(doc=>doc.filename).sort());
    for (const item of actual) assert.equal(item.json.title,group.documents.find(doc=>doc.filename===item.json.path.split('/').pop()).display_title);
  }
  const wa5480=allModels.filter(item=>item.json.model.folder==='WA5480 G3');
  const waCatalog=structuredClone(fresh.find(row=>row.folder==='WA5480 G3').body);
  const waManual=waCatalog.data.find(row=>row.url.endsWith('wa5480g3_user_guide_v8.pdf'));
  waManual.url=waManual.url.replace('_v8.pdf','_v9.pdf');waManual.updated='2026-10-06';
  const waCandidates=await run('Latest Document Families',[{json:{body:waCatalog}}],{'Models and Index':wa5480});
  assert.equal(waCandidates.length,11);
  const oldWa=combined.filter(item=>item.json.folder==='WA5480 G3');
  const waHtml='<script id="catalog-data" type="application/json">'+JSON.stringify({documents:oldWa.map(item=>({...item.json,remote_validator:{etag:'"wa"'}}))})+'</script>';
  const waChanges=await run('Changed Documents',waCandidates.map(()=>({json:{headers:{etag:'"wa"'}}})),{'Read INDEX':[{json:{data:waHtml}}],'Latest Document Families':waCandidates});
  assert.equal(waChanges.length,1);
  assert.equal(waChanges[0].json.old_path,'WA5480 G3/lenovo_wentian_wa5480g3_user_guide_v8.pdf');
  assert.equal(waChanges[0].json.path,'WA5480 G3/lenovo_wentian_wa5480g3_user_guide_v9.pdf');
  assert.equal(waChanges[0].json.previous_source_updated,'2026-03-27');
  const wa7880=allModels.find(item=>item.json.model.folder==='WA7880a G3').json.model;
  assert.equal(wa7880.fullGuid,g3Audit.models.find(group=>group.folder===wa7880.folder).fullGuid);
  assert(wa7880.fullGuid.endsWith('/6B5E239B-7F05-4E51-8A8E-CF69E0FB97C2'));
  const wr5225=allModels.filter(item=>item.json.model.folder==='WR5225 G3');
  const biosRows=fresh.find(row=>row.folder==='WR5225 G3').body.data.filter(row=>/-genoa\.pdf$|-turin\.pdf$/.test(row.url));
  assert.equal(biosRows.length,2);
  const future=structuredClone(biosRows[0]);
  future.url=future.url.replace('v3.0-genoa','v3.1-genoa');future.updated='2026-10-06';
  const editions=await run('Latest Document Families',[{json:{body:{data:[...biosRows,future]}}}],{'Models and Index':wr5225});
  const bios=editions.filter(item=>item.json.source==='asp');
  assert.equal(bios.length,2);
  const genoa=bios.find(item=>item.json.key.endsWith('/bios-setup-specification-genoa'));
  const turin=bios.find(item=>item.json.key.endsWith('/bios-setup-specification-turin'));
  assert(genoa.json.path.endsWith('v3.1-genoa.pdf'));assert(turin.json.path.endsWith('v2.9-turin.pdf'));
  const oldBios=combined.filter(item=>item.json.folder==='WR5225 G3'&&item.json.key.includes('/bios-'));
  const biosHtml='<script id="catalog-data" type="application/json">'+JSON.stringify({documents:oldBios.map(item=>({...item.json,remote_validator:{etag:'"bios"'}}))})+'</script>';
  const biosChanges=await run('Changed Documents',bios.map(()=>({json:{headers:{etag:'"bios"'}}})),{'Read INDEX':[{json:{data:biosHtml}}],'Latest Document Families':bios});
  assert.equal(biosChanges.length,1);
  assert(biosChanges[0].json.old_path.endsWith('v3.0-genoa.pdf'));
  assert(biosChanges[0].json.path.endsWith('v3.1-genoa.pdf'));
  assert.equal(biosChanges[0].json.title,oldBios.find(item=>item.json.key.endsWith('-genoa')).json.title);
  fs.writeFileSync(directory+'/expected-documents.json',JSON.stringify(combined.map(item=>item.json),null,2)+'\n');
  console.log('PASS: 14-model mapping, 95 unique model/document keys, audited current filenames/titles, independent Genoa/Turin updates and replacement paths');
  console.log('PASS: current-family deduplication, missing documents, same-URL ETag replacement, versioned filename replacement, stable labels, model isolation, HTML escaping, source failure stops processing');
})().catch(error=>{console.error(error);process.exitCode=1});
