#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE ${MATTERMOST_DB_USER} WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD '${MATTERMOST_DB_PASSWORD}';
    CREATE DATABASE ${MATTERMOST_DB_NAME} OWNER ${MATTERMOST_DB_USER};
    REVOKE CONNECT ON DATABASE ${MATTERMOST_DB_NAME} FROM PUBLIC;
    GRANT CONNECT ON DATABASE ${MATTERMOST_DB_NAME} TO ${MATTERMOST_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${MATTERMOST_DB_NAME} TO ${MATTERMOST_DB_USER};

    CREATE ROLE ${NEXTCLOUD_DB_USER} WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD '${NEXTCLOUD_DB_PASSWORD}';
    CREATE DATABASE ${NEXTCLOUD_DB_NAME} OWNER ${NEXTCLOUD_DB_USER};
    REVOKE CONNECT ON DATABASE ${NEXTCLOUD_DB_NAME} FROM PUBLIC;
    GRANT CONNECT ON DATABASE ${NEXTCLOUD_DB_NAME} TO ${NEXTCLOUD_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${NEXTCLOUD_DB_NAME} TO ${NEXTCLOUD_DB_USER};

    CREATE ROLE ${OPENPROJECT_DB_USER} WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD '${OPENPROJECT_DB_PASSWORD}';
    CREATE DATABASE ${OPENPROJECT_DB_NAME} OWNER ${OPENPROJECT_DB_USER};
    REVOKE CONNECT ON DATABASE ${OPENPROJECT_DB_NAME} FROM PUBLIC;
    GRANT CONNECT ON DATABASE ${OPENPROJECT_DB_NAME} TO ${OPENPROJECT_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${OPENPROJECT_DB_NAME} TO ${OPENPROJECT_DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${MATTERMOST_DB_NAME}" <<-EOSQL
    ALTER SCHEMA public OWNER TO ${MATTERMOST_DB_USER};
    GRANT ALL ON SCHEMA public TO ${MATTERMOST_DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${NEXTCLOUD_DB_NAME}" <<-EOSQL
    ALTER SCHEMA public OWNER TO ${NEXTCLOUD_DB_USER};
    GRANT ALL ON SCHEMA public TO ${NEXTCLOUD_DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${OPENPROJECT_DB_NAME}" <<-EOSQL
    ALTER SCHEMA public OWNER TO ${OPENPROJECT_DB_USER};
    GRANT ALL ON SCHEMA public TO ${OPENPROJECT_DB_USER};
    CREATE EXTENSION IF NOT EXISTS btree_gist;
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
    CREATE EXTENSION IF NOT EXISTS unaccent;
    GRANT ALL ON SCHEMA public TO ${OPENPROJECT_DB_USER};
EOSQL
